memory_buffer_size: 10000
viewer_type: "static"

encoder:
  type: "wheel"
  port: "COM4"
  baudrate: 57600
  cpr: 2400
  diameter_mm: 80
  sample_interval_ms: 20
  development_mode: True

nidaq:
  device_name: "Dev1"
  lines: "port2/line0"
  io_type: "DO"

cameras:
  - id: "dev"
    name: "devcam1"
    backend: "micromanager"
    micromanager_path: "C:/Program Files/Micro-Manager-2.0"


  - id: "dev"
    name: "devcam2"
    backend: "micromanager"
    micromanager_path: "C:/Program Files/Micro-Manager-2.0"



  # - id: "arducam"
  #   name: "arducam"
  #   backend: "opencv"
  #   properties:
  #     fps: 30