memory_buffer_size: 10000
viewer_type: "static"

nidaq:
  device_name: "Dev1"
  lines: "port1/line0"
  ctr: "ctr0"
  io_type: "DO"
  output:
    suffix: "nidaq"
    file_type: "csv"
  widgets:
    - "nidaq_test"

encoder:
  type: "wheel"
  port: "COM4"
  baudrate: 57600
  cpr: 2400
  diameter_mm: 80
  sample_interval_ms: 20
  development_mode: True

  output:
    suffix: "wheel"
    file_type: "csv"
    bids_type: "beh"

sensor:
  type: "lick"
  port: "COM5"
  baudrate: 115200
  capacitance_threshold: 100

  sample_interval_ms: 20
  development_mode: True

  output:
    suffix: "lick"
    file_type: "csv"
    bids_type: "beh"

cameras:
  - id: "Camera"
    name: "devcam1"
    backend: "micromanager"
    micromanager_path: "C:/Program Files/Micro-Manager-2.0"
    output:
      suffix: "devcam1"
      file_type: "ome.tiff"
      bids_type: "func"
    viewer_type: "static"
    properties:
      fps: 30
      Exposure: 30


  # - id: "dev"
  #   name: "devcam2"
  #   backend: "micromanager"
  #   micromanager_path: "C:/Program Files/Micro-Manager-thor"
  
    properties:
      Camera:
        fps: 30
        viewer_type: "static"


  # - id: "arducam"
  #   name: "arducam"
  #   backend: "opencv"
  #   properties:
  #     fps: 30